-- Grupito Seed Data
-- This file contains initial data for development and testing

-- Insert group categories
INSERT INTO group_categories (id, name_pt, name_en, icon, color, display_order) VALUES
('sports', 'Esportes', 'Sports', 'fitness', '#FF6B35', 1),
('food', 'Culinária', 'Food & Drink', 'restaurant', '#F7931E', 2),
('culture', 'Cultura', 'Arts & Culture', 'palette', '#9B59B6', 3),
('tech', 'Tecnologia', 'Technology', 'laptop', '#3498DB', 4),
('music', 'Música', 'Music', 'musical-notes', '#E74C3C', 5),
('books', 'Livros', 'Books & Literature', 'library', '#27AE60', 6),
('games', 'Jogos', 'Games', 'game-controller', '#8E44AD', 7),
('travel', 'Viagem', 'Travel', 'airplane', '#16A085', 8),
('business', 'Negócios', 'Business & Networking', 'briefcase', '#2C3E50', 9),
('outdoor', 'Atividades ao Ar Livre', 'Outdoor Activities', 'leaf', '#27AE60', 10),
('health', 'Saúde e Bem-estar', 'Health & Wellness', 'heart', '#E67E22', 11),
('education', 'Educação', 'Education & Learning', 'school', '#34495E', 12),
('volunteer', 'Voluntariado', 'Volunteering', 'hand-left', '#95A5A6', 13),
('photography', 'Fotografia', 'Photography', 'camera', '#F39C12', 14),
('other', 'Outros', 'Other', 'ellipsis-horizontal', '#7F8C8D', 15);

-- Note: The following are example seed data
-- In a real application, user profiles would be created through Clerk authentication
-- These examples are for development/testing purposes only

-- Example test user profiles (these would normally be created via Clerk)
-- INSERT INTO auth.users (id, email) VALUES
-- ('550e8400-e29b-41d4-a716-446655440000', 'maria@example.com'),
-- ('550e8400-e29b-41d4-a716-446655440001', 'joao@example.com');

-- Example profiles (uncomment and use real Clerk user IDs in development)
-- INSERT INTO profiles (id, display_name, bio, location_city, location_state) VALUES
-- ('550e8400-e29b-41d4-a716-446655440000', 'Maria Silva', 'Apaixonada por corrida e eventos esportivos', 'São Paulo', 'SP'),
-- ('550e8400-e29b-41d4-a716-446655440001', 'João Santos', 'Fotógrafo e organizador de eventos culturais', 'Rio de Janeiro', 'RJ');

-- Example groups (uncomment and use real user IDs)
-- INSERT INTO groups (id, name, description, category, visibility, created_by, location_city, location_state) VALUES
-- ('650e8400-e29b-41d4-a716-446655440000', 'Grupo de Corrida SP', 'Grupo para corredores de São Paulo que gostam de se exercitar em grupo', 'sports', 'public', '550e8400-e29b-41d4-a716-446655440000', 'São Paulo', 'SP'),
-- ('650e8400-e29b-41d4-a716-446655440001', 'Fotógrafos do Rio', 'Comunidade de fotógrafos do Rio de Janeiro', 'photography', 'public', '550e8400-e29b-41d4-a716-446655440001', 'Rio de Janeiro', 'RJ');

-- Example memberships (group creators automatically become members)
-- INSERT INTO memberships (user_id, group_id, role, status) VALUES
-- ('550e8400-e29b-41d4-a716-446655440000', '650e8400-e29b-41d4-a716-446655440000', 'creator', 'active'),
-- ('550e8400-e29b-41d4-a716-446655440001', '650e8400-e29b-41d4-a716-446655440001', 'creator', 'active');

-- Example events
-- INSERT INTO events (id, title, description, starts_at, group_id, created_by, location_name, location_address) VALUES
-- ('750e8400-e29b-41d4-a716-446655440000', 'Corrida Matinal no Ibirapuera', 'Corrida de 5km no Parque Ibirapuera', '2025-01-20 10:00:00+00', '650e8400-e29b-41d4-a716-446655440000', '550e8400-e29b-41d4-a716-446655440000', 'Parque Ibirapuera', 'Av. Paulista, 1578 - Bela Vista, São Paulo - SP'),
-- ('750e8400-e29b-41d4-a716-446655440001', 'Workshop de Fotografia Urbana', 'Aprenda técnicas de fotografia urbana no centro do Rio', '2025-01-25 14:00:00+00', '650e8400-e29b-41d4-a716-446655440001', '550e8400-e29b-41d4-a716-446655440001', 'Centro Cultural Banco do Brasil', 'Rua Primeiro de Março, 66 - Centro, Rio de Janeiro - RJ');

-- Development notes:
-- 1. User IDs should come from Clerk authentication
-- 2. Use proper UUID values generated by uuid_generate_v4()
-- 3. All timestamps should be in UTC
-- 4. Location coordinates can be added using PostGIS functions if needed
-- 5. Real profile data should be created through the mobile app registration flow